### ISSUE TITLE
Every cave is an elemental cave.

### ISSUE THREAD

**Issue by Delocuro** [MinestrapTeam/Elemental-Caves#27]
Currently, the only place you can find regular caves is in cold biomes, since snow, mild, and warm biomes only ever spawn elemental caves. While the elemental caves are the main feature of the mod, having every single cave turn into an elemental cave sort of ruins the entire game's balance and progression...

**Comment by Clashsoft** [comment]
Elemental caves only spawn in Hot, Cold and Forest Biomes.
