### ISSUE TITLE
Missing Blocks

### ISSUE THREAD

**Issue by Delocuro** [MinestrapTeam/Elemental-Caves#29]
Glacierrock Brick Slabs, Moltenstone Brick Slabs, Molten Diamond Ore, Ancient Moss Stone Brick Stairs, Ancient Mossy Cobblestone Stairs, Mossy Iron Ore, Fertile Ore, Golden Oak Leaves, and Golden Oak Saplings are not yet implemented.

**Comment by Clashsoft** [comment]
Glacierrock Bricks Slabs and Moltenstone Brick Slabs are implemented now.
