### ISSUE TITLE
Icefloe and Lava incorrect collision results.

### ISSUE THREAD

**Issue by Delocuro** [MinestrapTeam/Elemental-Caves#37]
Flowing Icefloe hitting Flowing Lava currently makes Cobblestone rather than Cracked Glacierrock, and Flowing Lava hitting Flowing Icefloe from above currently makes Stone rather than Glacierrock.

**Comment by Clashsoft** [comment]
Flowing Lava hitting Flowing Icefloe from above makes Glacierrock now. Flowing Icefloe hitting Flowing Lava is not fixable, since the Lava checks for the Ice Floe and sets itself to Obsidian / Cobblestone.
